import Card from '../ui/Card'
import { getWorkdayStatus } from '../../utils/profileMetrics'

const width = 840, height = 250, left = 42, right = 20, top = 24, bottom = 38

export default function WeeklyHoursTrend({ records, selectedWeek, onSelectWeek }) {
  const available = records.filter(Boolean)
  if (!available.length) return null
  const maxHours = Math.ceil(Math.max(...available.flatMap(row => [row.expectedHours, row.workedHours]), 1) / 5) * 5
  const plotWidth = width - left - right, plotHeight = height - top - bottom
  const x = week => left + ((week - 1) / 13) * plotWidth
  const y = value => top + plotHeight - (value / maxHours) * plotHeight
  const line = key => available.map(row => `${x(row.week)},${y(row[key])}`).join(' ')
  const selected = records.find(row => row?.week === selectedWeek)
  return <Card className="overflow-hidden"><header className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-100 p-6"><div><h2 className="font-semibold">Weekly Hours Trend</h2><p className="mt-1 text-xs text-muted">Expected and worked hours across the semester</p></div><div className="flex gap-4 text-xs"><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-slate-400" />Expected</span><span className="flex items-center gap-1.5"><i className="size-2 rounded-full bg-blue-600" />Worked</span></div></header><div className="overflow-x-auto px-3 pb-3"><svg className="min-w-[760px]" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Weekly expected and worked hours trend"><g>{[0,.25,.5,.75,1].map(mark => {const value=Math.round(maxHours*mark);return <g key={mark}><line x1={left} x2={width-right} y1={y(value)} y2={y(value)} className="stroke-slate-100" /><text x={left-9} y={y(value)+4} textAnchor="end" className="fill-slate-400 text-[10px]">{value}</text></g>})}</g>{selected&&<rect x={x(selectedWeek)-18} y={top-7} width="36" height={plotHeight+14} rx="6" className="fill-blue-50" />}<polyline points={line('expectedHours')} fill="none" className="stroke-slate-400" strokeWidth="2" strokeDasharray="5 5" /><polyline points={line('workedHours')} fill="none" className="stroke-blue-600" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round" />{available.map(row => <g key={row.week} className="cursor-pointer" tabIndex="0" role="button" aria-label={`Week ${row.week}: ${row.workedHours} worked of ${row.expectedHours} expected`} onClick={()=>onSelectWeek(row.week)} onKeyDown={event=>['Enter',' '].includes(event.key)&&onSelectWeek(row.week)}><circle cx={x(row.week)} cy={y(row.workedHours)} r={row.week===selectedWeek?6:4} className={row.week===selectedWeek?'fill-blue-600 stroke-white':'fill-white stroke-blue-600'} strokeWidth="2"><title>{`Week ${row.week}\nWorked: ${row.workedHours} hrs\nExpected: ${row.expectedHours} hrs\nDifference: ${(row.workedHours-row.expectedHours).toFixed(2)} hrs\nStatus: ${getWorkdayStatus(row)}`}</title></circle><text x={x(row.week)} y={height-14} textAnchor="middle" className={row.week===selectedWeek?'fill-blue-700 text-[10px] font-semibold':'fill-slate-400 text-[10px]'}>{row.week}</text></g>)}</svg></div>{selected&&<footer className="grid grid-cols-2 gap-3 border-t border-slate-100 bg-slate-50 px-6 py-3 text-xs sm:grid-cols-4"><TrendDetail label="Selected" value={`Week ${selected.week}`} /><TrendDetail label="Worked" value={`${selected.workedHours} hrs`} /><TrendDetail label="Expected" value={`${selected.expectedHours} hrs`} /><TrendDetail label="Difference" value={`${selected.workedHours-selected.expectedHours>0?'+':''}${(selected.workedHours-selected.expectedHours).toFixed(2)} hrs`} /></footer>}</Card>
}

function TrendDetail({ label, value }) { return <div><span className="text-muted">{label}</span><strong className="ml-2 text-slate-800">{value}</strong></div> }
